# Generated by Django 2.2 on 2019-11-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût global')),
                ('duree_exevution', models.CharField(max_length=20, verbose_name='Durée exécution en mois')),
                ('lieu', models.CharField(max_length=200, verbose_name='Lieu implantation')),
                ('milieu', models.CharField(choices=[('R', 'Rural'), ('U', 'Urbain')], max_length=100)),
            ],
        ),
    ]
