# Generated by Django 2.2 on 2019-11-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='duree_exevution',
            new_name='duree_execution',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='lieu',
        ),
    ]
